services:
  raccoon-api:
    container_name: raccoon-api
    image: ghcr.io/lotusotho/raccoon-api:main
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./dumpster:/app/dumpster
    networks:
      - raccoon-net

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./dumpster:/dumpster
      - ./logs:/var/log/caddy  # Volumen para los logs
    depends_on:
      - raccoon-api
    networks:
      - raccoon-net

  goaccess:
    image: allinurl/goaccess
    container_name: goaccess
    restart: always
    ports:
      - "7890:7890"
    volumes:
      - ./logs:/srv/logs:ro
    command:
      - /srv/logs/access.log
      - --log-format=COMBINED
      - --real-time-html
      - --port=7890
      - --address=0.0.0.0
    networks:
      - raccoon-net

volumes:
  caddy_data:
  caddy_config:

networks:
  raccoon-net:
    name: raccoon-net
    driver: bridge